# Generated by Django 4.0.4 on 2023-01-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=30)),
                ('name_ar', models.CharField(max_length=30)),
                ('name_jp', models.CharField(max_length=30)),
                ('active', models.BooleanField(verbose_name=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('WA', 'WATER'), ('GR', 'grass'), ('GH', 'ghost'), ('ST', 'steel'), ('FA', 'fairy')], default='WA', max_length=2)),
            ],
        ),
    ]
