# Generated by Django 4.0.4 on 2023-01-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_alter_pokemon_name_ar_alter_pokemon_name_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
