# Generated by Django 4.0.4 on 2023-01-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_pokemon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
