# Generated by Django 4.0.4 on 2023-01-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0007_alter_pokemon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('WA', 'WATER'), ('GR', 'grass'), ('GH', 'ghost'), ('ST', 'steel'), ('FA', 'fairy')], max_length=2),
        ),
    ]
